name: ci

on: push

jobs:
  ci:
    name: ci
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"
          node-version: 12
      - name: install dependencies
        run: npm ci
      - name: commitlint
        run: npx commitlint -f origin/master -V
      - name: lint n' style
        run: npm run style:check && npm run tslint:check && npm run eslint:check
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: release
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
