name: ci

on: push

jobs:
  ci:
    name: ci
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"
          node-version: 12
      - name: cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          # https://github.com/actions/cache/issues/67
          # https://github.com/actions/cache/pull/69#issuecomment-553176365
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package*.json') }}
      - name: install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: commitlint
        run: npx commitlint -f origin/master -V
      - name: lint n' style
        run: npm run lint:check
      - name: cache dist
        uses: actions/cache@v2
        with:
          path: dist
          key: ${{ runner.os }}-dist-${{ github.sha }}
          restore-keys: ${{ runner.os }}-dist-
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: release
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
